---
AWSTemplateFormatVersion: "2010-09-09"
Description: This template create a RDS mysql instance

Parameters:
  AccountName:
    Type: String
  CostCenter:
    Type: String
  Environment:
    Type: String
  Owner:
    Type: String
  Project:
    Type: String
  
  VPC: 
    Description: Select VPC
    Type: "AWS::EC2::VPC::Id"
    
  SubnetIDs: 
    Description: 2 Subnet IDs (comma separated)
    Type: "List<AWS::EC2::Subnet::Id>"

  InstanceType:
    Description: Databse EC2 instance type
    Type: String
    Default: db.m6g.large

  DBEngine:
    Type: String
    Default: "mysql"

  DBEngineVersion:
    Type: String
    Default: "5.7.38"

  DBStorageType:
    Type: String

  DBAllocatedStorage:
    Type: Number
    Default: 256

  VPCCidr:
    Type: String
    Description: VPC CIDR
  
  SnapshotID:
    Type: String
    Description: Snapshot ID
    Default: ""
  
  DatabaseRole:
    Type: String
    Description: Define if creates or not a DB role
    Default: ""
  
  MultiAZ:
    Type: String
    Description: Optional configuration for a Multi AZ Database setup. Default configuration is a single instance. The Multy AZ option will configure a standby instance in the second subnets.
    AllowedPattern: "^(true|false)$"
    Default: "false"
    ConstraintDescription: must be true or false (case sensitive).
  
  Username:
    Type: String
    NoEcho: True
    Default: ""
  
  Password:
    Type: String
    Description: The name of the encrypted Parameter store where the db password is saved
    Default: ""
  
  KMSKeyID:
    Type: String
    Description: The KMS key used to encrypt the cluster
    Default: ""
  
  TopicArn:
    Type: String
    Description: The ARN of the SNS topic where sending the alarms notification
    Default: ""

Conditions:

  RestoreFromSnap: !Not [!Equals [!Ref SnapshotID, ""]]
  HasRole: !Not [!Equals [!Ref DatabaseRole, ""]]
  HasAlertTopic: !Not [!Equals [!Ref TopicArn, '']]

Resources:

  ParameterGroup:
    Type: AWS::RDS::DBParameterGroup
    Properties:
      Family: mysql8.0
      Description: "Parameter group used by the RDS db"
      Parameters:
        binlog_cache_size: 512000
      Tags:
        - Key: AccountName
          Value: !Ref AccountName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project

  #SUBNET GROUP FROM SUBNET IDS
  DBSubnetGroup:
    Properties:
      DBSubnetGroupDescription: DBSubnetGroup for RDS instances
      SubnetIds:
        - !Select [0, !Ref SubnetIDs]
        - !Select [1, !Ref SubnetIDs]
        - !Select [2, !Ref SubnetIDs]
    Type: AWS::RDS::DBSubnetGroup

  #DB SECURITY GROUP
  DBSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupDescription: !Sub Allow traffic for ${Project}-${Environment} to the database
      VpcId: !Ref VPC
      GroupName: !Sub ${Project}-${Environment}-db-sg
      SecurityGroupIngress:
        - IpProtocol: TCP
          ToPort: 3306
          FromPort: 3306
          CidrIp: !Ref VPCCidr
      SecurityGroupEgress:
        - IpProtocol: TCP
          ToPort: 3306
          FromPort: 3306
          CidrIp: !Ref VPCCidr
      Tags:
        - Key: AccountName
          Value: !Ref AccountName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Name
          Value: !Sub ${Project}-${Environment}-db-sg
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
    
  Database:
    Type: AWS::RDS::DBInstance
    DeletionPolicy: Retain
    UpdateReplacePolicy: Retain
    Properties:
      DBInstanceIdentifier: !Sub ${Project}-${Environment}
      AllocatedStorage: !Ref DBAllocatedStorage
      BackupRetentionPeriod: 30
      DBInstanceClass: !Ref InstanceType
      StorageType: !Ref DBStorageType
      Engine: !Ref DBEngine
      EngineVersion: !Ref DBEngineVersion
      PubliclyAccessible: False
      VPCSecurityGroups:
      - !Ref DBSecurityGroup
      DBSubnetGroupName: !Ref DBSubnetGroup
      DBParameterGroupName: !Ref ParameterGroup
      EnableCloudwatchLogsExports:
      - error
      - general
      - slowquery
      - audit
      DBSnapshotIdentifier: !If 
      - RestoreFromSnap
      - !Ref SnapshotID
      - !Ref AWS::NoValue
      MasterUsername: !If
      - RestoreFromSnap
      - !Ref AWS::NoValue
      - !Ref Username
      MasterUserPassword: !If
      - RestoreFromSnap
      - !Ref AWS::NoValue
      - !Sub "{{resolve:ssm-secure:${Password}}}"
      KmsKeyId: !If
      - RestoreFromSnap
      - !Ref AWS::NoValue
      - !Ref KMSKeyID
      StorageEncrypted: !If
      - RestoreFromSnap
      - !Ref AWS::NoValue
      - true
      AssociatedRoles: !If 
      - HasRole
      - - FeatureName: s3Export
          RoleArn: !Ref DatabaseRole
      - !Ref AWS::NoValue
      MultiAZ: !Ref MultiAZ
      Tags:
        - Key: AccountName
          Value: !Ref AccountName
        - Key: CostCenter
          Value: !Ref CostCenter
        - Key: Environment
          Value: !Ref Environment
        - Key: Owner
          Value: !Ref Owner
        - Key: Project
          Value: !Ref Project
  
  DatabaseBurstBalanceTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database storage burst balance over last 10 minutes lower than 20%, expect a significant performance drop soon'
      Namespace: 'AWS/RDS'
      MetricName: BurstBalance
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 20
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database

  DatabaseCPUUtilizationTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database CPU utilization over last 10 minutes higher than 80%'
      Namespace: 'AWS/RDS'
      MetricName: CPUUtilization
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 80
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database

  DatabaseDiskQueueDepthTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database disk queue depth over last 10 minutes higher than 64, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: DiskQueueDepth
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 64
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database

  DatabaseFreeableMemoryTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database freeable memory over last 10 minutes lower than 64 MB, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: FreeableMemory
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 67108864 # 64 MB in Bytes
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  
  DatabaseFreeStorageSpaceTooLowAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database free storage space over last 10 minutes lower than 2 GB'
      Namespace: 'AWS/RDS'
      MetricName: FreeStorageSpace
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: LessThanThreshold
      Threshold: 2147483648 # 2 GB in Bytes
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database
  
  DatabaseSwapUsageTooHighAlarm:
    Condition: HasAlertTopic
    Type: 'AWS::CloudWatch::Alarm'
    Properties:
      AlarmDescription: 'Average database swap usage over last 10 minutes higher than 256 MB, performance may suffer'
      Namespace: 'AWS/RDS'
      MetricName: SwapUsage
      Statistic: Average
      Period: 600
      EvaluationPeriods: 1
      ComparisonOperator: GreaterThanThreshold
      Threshold: 268435456 # 256 MB in Bytes
      AlarmActions:
      - !Ref TopicArn
      Dimensions:
      - Name: DBInstanceIdentifier
        Value: !Ref Database